apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "giga-blocks.fullname" . }}-admin-conf
  namespace: {{ .Release.Namespace }}
data:
  .env_temp: |
{{- range $key, $val := .Values.admin.config }}
    {{ $key }}={{ $val | quote }}
{{- end }}
