apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "giga-blocks.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "giga-blocks.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "giga-blocks.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "giga-blocks.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["/bin/ash"]
          args: ["-c", "cd /usr/src/app && cp /tmp/.env_temp .env && env | grep -Ei \"(password|secret|token|key)\" >> /usr/src/app/.env; npm start" ]
          volumeMounts:
          - name: config
            mountPath: /tmp/
          env:
            - name: env
              value: {{ .Values.environment }}
            - name: SERVICE_NAME
              value: {{ include "giga-blocks.fullname" . }}
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            {{- range .Values.api.envSecrets }}
            - secretRef:
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- range .Values.api.envConfigMaps }}
            - configMapRef:
                {{- toYaml . | nindent 16 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
              protocol: TCP
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "giga-blocks.fullname" . }}-api-conf
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
