apiVersion: v1
kind: Service
metadata:
  name: {{ include "giga-blocks.name" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "giga-blocks-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: {{ .Values.admin.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "giga-blocks-admin.selectorLabels" . | nindent 4 }}
