apiVersion: v1
kind: Service
metadata:
  name: {{ include "giga-blocks.name" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "giga-blocks-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "giga-blocks-web.selectorLabels" . | nindent 4 }}
