apiVersion: v1
kind: Service
metadata:
  name: {{ include "giga-blocks.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "giga-blocks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "giga-blocks.selectorLabels" . | nindent 4 }}
