name: Dev Web CD/CD
on:
  push:
    branches:
      - 'dev'
    paths:
      - 'apps/web/**'  
  pull_request:
    branches:
      - 'dev'
    paths:
      - 'apps/web/**' 

env:
  CI: false
  env_dev: ${{ secrets.ENV_DEV }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev

      - name: import env file
        run: |
          touch ./.env && echo "$env_dev" >> ./.env
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm
          pnpm install
          npx nx build web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push web
        id: build-push-web
        uses: docker/build-push-action@v3
        if: github.event_name == 'push'
        with:
          context: .
          file: Dockerfile.web
          push: true
          tags: rumsan/giga-mono-ntf2-web:dev

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} .
