name: Stage Admin CD/CD
on:
  push:
    branches:
      - 'stage'
    paths:
      - 'apps/admin/**'
  pull_request:
    branches:
      - 'stage'
    paths:
      - 'apps/admin/**'

env:
  CI: false
  env_stage: ${{ secrets.ENV_STAGE }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stage

      - name: import env file
        run: |
          touch ./.env && echo "$env_stage" >> ./.env

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm
          pnpm install
          npx nx build admin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push admin
        id: build-push-admin
        uses: docker/build-push-action@v3
        if: github.event_name == 'push'
        with:
          context: .
          file: Dockerfile.admin
          push: true
          tags: rumsan/giga-mono-ntf2-admin:stage

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -f Dockerfile.admin -t myimage:${{ github.sha }} .
